# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:17
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('log_and_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('register_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
