# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_and_reg', '0002_auto_20170719_0517'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
