# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_auto_20170716_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
    ]
