# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logged_in',
        ),
    ]
