# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0003_remove_dojo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='brief description of dojo'),
            preserve_default=False,
        ),
    ]
